module.exports = {
    methods: {
        get: 'GET',
        post: 'POST',
        put: 'PUT',
        delete: 'DELETE'
    },
    baseUrl: 'https://plug.dj/',
    endpoints: {
        csrf: '',
        news: '/_/news',
        bans: '/_/bans',
        staff: '/_/staff',
        rooms: '/_/rooms',
        mutes: '/_/mutes',
        token: '/_/auth/token',
        friends: '/_/friends',
        history: '/_/rooms/history',
        ignores: '/_/ignores',
        invites: '/_/friends/invites',
        products: '/_/store/products',
        inventory: '/_/store/inventory',
        roomstats: '/_/rooms/state',
        userstats: '/_/users/',
        playlists: '/_/playlists',
        userhistory: '/_/users/me/history',
        transaction: '/_/users/me/transactions',
        favoriteRooms: '/_/rooms/favorites',
        validateUser: '/_/users/validate/',
        validateRoom: '/_/rooms/validate/',

        lock: '/_/booth/lock',
        blurb: '/_/profile/blurb',
        cycle: '/_/booth/cycle',
        login: '/_/auth/login',
        badge: '/_/users/badge',
        avatar: '/_/users/avatar',
        settings: '/_/users/settings',
        language: '/_/users/language',
        ignorefirend: '/_/friends/ignore',

        grabs: '/_/grabs',
        votes: '/_/votes',
        reset: '/_/auth/reset/me',
        purchase: '/_/store/purchase',
        facebook: '/_/auth/facebook',
        joinRoom: '/_/rooms/join',
        addBooth: '/_/booth/add',
        bulkUsers: '/_/users/bulk',
        joinBooth: '/_/booth',
        skip: '/_/booth/skip',
        move: '/_/booth/move',
        createRoom: '/_/rooms',
        updateRoom: '/_/rooms/update',
        updateStaff: '/_/staff/update',

        chat: '/_/chat/',
        session: '/_/auth/session',
        remove: '/_/booth/remove/',
        notification: '/_/notifications/'
    },
    socket:'wss://godj.plug.dj/socket',
    packetTypes:{
        auth:'auth'
    }, invalidRooms:['dashboard','ba','about','terms']
};